# Generated by Django 2.2.2 on 2019-06-27 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='orfForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_names', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('feedback', models.CharField(max_length=100)),
                ('customer_address', models.CharField(max_length=200)),
                ('date', models.CharField(max_length=100)),
                ('work_order_no', models.CharField(max_length=100)),
                ('quotation_ref_no', models.CharField(max_length=100)),
                ('quotation_date', models.CharField(max_length=100)),
                ('project_title', models.CharField(max_length=100)),
                ('job_details', models.CharField(max_length=100)),
                ('project_order_value', models.CharField(max_length=100)),
                ('payment_terms', models.CharField(max_length=100)),
                ('job_duration', models.CharField(max_length=100)),
                ('job_starting_date', models.CharField(max_length=100)),
                ('job_completion_date', models.CharField(max_length=100)),
                ('expected_precom_date', models.CharField(max_length=100)),
                ('expected_com_date', models.CharField(max_length=100)),
                ('handover_date_exp', models.CharField(max_length=100)),
                ('handover_date_act', models.CharField(max_length=100)),
                ('name_of_project_incharge', models.CharField(max_length=100)),
                ('name_of_site_incharge', models.CharField(max_length=100)),
                ('advance_payment', models.CharField(max_length=100)),
                ('particulars', models.CharField(max_length=100)),
                ('budgeted_amount', models.CharField(max_length=100)),
                ('actual_amount', models.CharField(max_length=100)),
                ('variance', models.CharField(max_length=100)),
                ('remarks', models.CharField(max_length=100)),
                ('notes', models.CharField(max_length=100)),
                ('total_cost', models.CharField(max_length=100)),
                ('amount_to_be_paid_cash', models.CharField(max_length=100)),
                ('amount_to_be_paid_cheque', models.CharField(max_length=100)),
            ],
        ),
    ]
